# CodeRabbit Configuration for Islanders Cricket Club PWA
# https://docs.coderabbit.ai/guides/configure-coderabbit

language: "en-US"
early_access: false
enable_free_tier: true

reviews:
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  poem: true
  review_status: true
  collapse_walkthrough: false

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
      - master

  path_instructions:
    - path: "src/lib/azure.ts"
      instructions: |
        **CRITICAL REVIEW - Azure Blob Storage Integration**
        - Blob upload/download error handling
        - SAS token security and expiration
        - File type validation for photo uploads
        - Race conditions in concurrent operations
        - Memory leaks in blob streaming
        - CORS configuration compatibility

    - path: "src/services/playerService.ts"
      instructions: |
        **Player Data Management**
        - JSON parsing error handling
        - Cache invalidation strategy
        - Concurrent update handling
        - Data consistency checks
        - Performance optimization opportunities

    - path: "src/hooks/**"
      instructions: |
        **React Hooks Review**
        - Memory leak prevention (cleanup functions)
        - Dependency array correctness
        - Error state handling
        - Loading state management
        - Re-render optimization

    - path: "src/pages/**"
      instructions: |
        **UI/UX Review**
        - Accessibility (ARIA labels, keyboard navigation)
        - Loading states and error messages
        - Mobile responsiveness
        - Performance (lazy loading, code splitting)

    - path: "**/*.ts"
      instructions: |
        - TypeScript type safety
        - Null/undefined handling
        - Error handling patterns
        - Code organization

    - path: "**/*.tsx"
      instructions: |
        - React best practices
        - Component composition
        - Props validation
        - Performance optimization

  knowledge_base:
    - "PWA cricket team management app for Islanders Cricket Club"
    - "Firebase Auth for Google Sign-In ONLY"
    - "Azure Blob Storage for ALL data (players, matches, photos)"
    - "Direct writes allowed - NO approval queue"
    - "Players stored as individual JSON files (players/akhil.json)"
    - "Photos stored in photos/ folder with Azure Blob"
    - "Contact: canderson@hssmedicine.com"
    - "Target: Simple, fast, mobile-first PWA"

chat:
  auto_reply: true

checks:
  complexity:
    enabled: true
    threshold: 15

  documentation:
    enabled: true
    missing_docstrings: true

  security:
    enabled: true
    scan_dependencies: true

  performance:
    enabled: true
    flag_inefficient_loops: true

tools:
  eslint:
    enabled: true

tone_instructions: "Be constructive, explain WHY, provide examples, prioritize high-impact issues"

custom_rules:
  - name: "API Key Security"
    pattern: "(FIREBASE_API_KEY|AZURE_STORAGE_SAS_TOKEN)\\s*=\\s*['\"](?!import\\.meta)"
    message: "Potential hardcoded API key. Use environment variables."
    severity: "high"

  - name: "Missing Error Handling"
    pattern: "await.*(?!try|catch)"
    message: "Consider wrapping async calls in try-catch"
    severity: "medium"

exclude:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"

notifications:
  review_complete: true
  new_issue: true
